name: Download Cache
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      cache_dir: "cache/"
    steps:
      - name: Get Date
        id: get-date
        run: |
          /bin/date
          echo "date=$(/bin/date -u "+%Y%m%d%H%M")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Atlas and wiki data
        uses: actions/cache@v3
        with:
          path: ${{ env.cache_dir }}
          fail-on-cache-miss: false
          key: api-cache-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            api-cache-${{ runner.os }}-
            api-cache-

      - uses: yizhoumo/setup-ossutil@v1
        with:
          ossutil-version: "1.7.9"
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Download from OSS
        run: ossutil cp oss://${{ secrets.OSS_BUCKET_NAME }}/cache/chaldea_parser_cache.tar.gz chaldea_parser_cache.tar.gz

      - name: Extra cache
        run: |
          mkdir -p ${{ env.cache_dir }}
          tar -xzvf chaldea_parser_cache.tar.gz -C ${{ env.cache_dir }}
          ls -lR ${{ env.cache_dir }}
