name: Upload Cache
on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-20.04
    env:
      cache_dir: "cache/"
    steps:
      - name: Get Date
        id: get-date
        run: |
          /bin/date
          echo "date=$(/bin/date -u "+%Y%m%d%H%M")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Atlas and wiki data
        uses: actions/cache@v3
        with:
          path: ${{ env.cache_dir }}
          fail-on-cache-miss: true
          key: api-cache-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            api-cache-${{ runner.os }}-
            api-cache-

      - uses: yizhoumo/setup-ossutil@v1
        with:
          ossutil-version: "1.7.9"
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Compress cache
        run: tar --exclude ".*"  -cvzf $GITHUB_WORKSPACE/chaldea_parser_cache.tar.gz wiki http_cache
        working-directory: ${{ env.cache_dir }}

      - name: Upload to OSS
        run: ossutil cp chaldea_parser_cache.tar.gz oss://${{ secrets.OSS_BUCKET_NAME }}/cache/chaldea_parser_cache.tar.gz -f
