name: Wiki Parser
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '15 1 * * *'

jobs:
  wiki:
    runs-on: ubuntu-latest
    env:
      output_dir: 'data/'
      cache_dir: 'cache/'
      static_dir: 'static/'
    steps:
      - name: Get Date
        id: get-date
        run: |
          /bin/date
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d%H%M")"
        shell: bash

      - name: Checkout chaldea-parser
        uses: actions/checkout@v2

      - name: Checkout data repo
        uses: actions/checkout@v2
        with:
          repository: chaldea-center/chaldea-data
          token: ${{ secrets.GH_PAGES_TOKEN }}
          path: ${{ env.output_dir }}

      - name: Checkout static repo
        uses: actions/checkout@v2
        with:
          repository: chaldea-center/static-resource
          token: ${{ secrets.GH_PAGES_TOKEN }}
          path: ${{ env.static_dir }}

      - name: Cache Atlas and wiki api response
        uses: actions/cache@v2
        with:
          path: ${{ env.cache_dir }}
          key: api-cache-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            api-cache-${{ runner.os }}-
            api-cache-

      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip uninstall --yes fgo-game-data-api
          pip install -r requirements.txt

      - name: run wiki parser
        run: python main.py wiki

      - name: publish wiki data
        id: publish-data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          cd ${{ env.output_dir }}
          cat .git/refs/heads/main
          echo "::set-output name=ref1::$(cat .git/refs/heads/main)"
          git add .
          git commit -m "wiki parser: update data" || echo "Nothing to update"
          git push
          cat .git/refs/heads/main
          echo "::set-output name=ref2::$(cat .git/refs/heads/main)"
          cd ..

      - name: publish static
        run: |
          cd ${{ env.static_dir }}
          git add .
          git commit -m "update static files" || echo "Nothing to update"
          git push
          cd ..

      - name: run atlas parser
        run: python main.py atlas

      - name: publish data
        run: |
          cd ${{ env.output_dir }}
          git add .
          if [ -e commit-msg.txt ]
          then
              git commit -F commit-msg.txt || echo "Nothing to update"
          else
              git commit -m "atlas parser: update data" || echo "Nothing to update"
          fi
          git push
          cd ..